using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using quiz_app.Models;
using System;
using System.IO;
using System.Linq;

namespace quiz_app.Services
{
    public class PdfExportService
    {
        public byte[] GenerateQuizResultPdf(QuizResult result)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(50);
                    page.Size(PageSizes.A4);

                    // Header
                    page.Header().Text($"Quiz Result – {result.UserName}")
                        .FontSize(20)
                        .Bold();

                    // Main content
                    page.Content().Column(col =>
                    {
                        col.Item().Text($"Date: {result.DateTaken:yyyy-MM-dd HH:mm}");
                        col.Item().Text($"Score: {result.Score}");

                        col.Item().PaddingVertical(10).LineHorizontal(1);

                        // Section title
                        col.Item().Text("Answers:")
                            .FontSize(16)
                            .Bold();

                        foreach (var answer in result.Answers)
                        {
                            bool isCorrect = answer.SelectedAnswer == answer.CorrectAnswer;

                            col.Item().Text($"Q: {answer.Question}")
                                .FontSize(12);

                            col.Item().Text(text =>
                            {
                                text.Span("Your answer: ").FontSize(12).Italic();
                                text.Span(answer.SelectedAnswer)
                                    .FontSize(12)
                                    .Italic()
                                    .FontColor(isCorrect ? "#2E7D32" : "#C62828");
                            });

                            if (!isCorrect)
                            {
                                col.Item().Text(text =>
                                {
                                    text.Span("Correct answer: ").FontSize(12).Italic();
                                    text.Span(answer.CorrectAnswer)
                                        .FontSize(12)
                                        .Italic()
                                        .FontColor("#2E7D32");
                                });
                            }

                            col.Item().PaddingBottom(10);
                        }
                    });

                    // Footer
                    page.Footer().AlignCenter().Text("Generated by Quiz App – Mystical Learning");
                });
            });

            return document.GeneratePdf(); 
        }
    }
}
