// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using quiz_app;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250704105700_InitCleanAgain")]
    partial class InitCleanAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("quiz_app.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("quiz_app.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswer = "Tea",
                            Options = "Orange juice,Water,Tea,Milk",
                            Text = "Which of these drinks usually contains caffeine?",
                            Type = "multiple"
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswer = "Seaweed",
                            Options = "Seaweed,Lettuce,Rice paper,Plastic",
                            Text = "What is sushi traditionally wrapped in?",
                            Type = "multiple"
                        },
                        new
                        {
                            Id = 3,
                            CorrectAnswer = "Listening to calming music",
                            Options = "Listening to calming music,Eating more sugar,Skipping sleep,Arguing online",
                            Text = "Which of these is a common way to reduce stress?",
                            Type = "multiple"
                        },
                        new
                        {
                            Id = 4,
                            CorrectAnswer = "Honey",
                            Options = "Honey,Butter,Oil,Milk",
                            Text = "What do bees produce?",
                            Type = "multiple"
                        },
                        new
                        {
                            Id = 5,
                            CorrectAnswer = "Apple",
                            Options = "Apple,Lettuce,Carrot,Broccoli",
                            Text = "Which of these is considered a fruit?",
                            Type = "multiple"
                        },
                        new
                        {
                            Id = 6,
                            CorrectAnswer = "France",
                            Options = "France,Italy,Germany,Spain",
                            Text = "Which country is famous for the Eiffel Tower?",
                            Type = "multiple"
                        },
                        new
                        {
                            Id = 7,
                            CorrectAnswer = "Computer",
                            Options = "Computer,Microwave,Television,Oven",
                            Text = "What do you use to send an email?",
                            Type = "multiple"
                        },
                        new
                        {
                            Id = 8,
                            CorrectAnswer = "Sunlight",
                            Options = "Sunlight,Darkness,Plastic,Smoke",
                            Text = "What helps plants grow?",
                            Type = "multiple"
                        },
                        new
                        {
                            Id = 9,
                            CorrectAnswer = "Guitar",
                            Options = "Guitar,Plate,Chair,Spoon",
                            Text = "Which one is a musical instrument?",
                            Type = "multiple"
                        },
                        new
                        {
                            Id = 10,
                            CorrectAnswer = "Cereal",
                            Options = "Cereal,Pizza,Steak,Popcorn",
                            Text = "What is a common breakfast food?",
                            Type = "multiple"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
